server:
  port: 7490
spring:
  application:
    name: ATool
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.2:3306/atool
    username: root
    password: wei5877261
  data:
    redis:
      database: 0
      host: 192.168.5.2
      port: 6379
      password: wei5877261
      timeout: 1800
  mail:
    host: smtp.qq.com
    username: 3684779724@qq.com
    password: ogrzjsznsjxdciic
    port: 465
    protocol: smtp
    ssl:
      enabled: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback.xml

forest:
  backend: okhttp3
  log-response-status: false
  log-request-body: true
  log-request-headers: false
  log-response-headers: false
  log-response-content: true

################# 自定义属性 ###############
atool:
  captcha:
    captcha-len: 6
    types:
      - email
      - phone
    expire: 120 #有效期
    expire-unit: seconds
    resend-in: 60 #可重发时间
    resend-unit: seconds
    email-template: classpath*:/templates/captcha.html
  regex-check:
    regex:
      email: ^[^\s@]+@[^\s@]+\.[^\s@]+$
      phone: ^(?:(?:\+|00)86)?1(?:(?:3[\d])|(?:4[5-79])|(?:5[0-35-9])|(?:6[5-7])|(?:7[0-8])|(?:8[\d])|(?:9[01256789]))\d{8}$
      password : ^(?=.*[a-zA-Z])(?=.*[0-9])[a-zA-Z0-9!@#$%^&*_+\-=]{6,24}$
  jwt:
    key: e372d98n3weriuiwetryueitbryuestyve487btv43e
    expire: 604800
    unit: seconds

  lottery:
    min: 25
    max: 65
  epay:
    key: U51Sy51Pi5XuSSorU159FSS71sOURVsR
    return-url: http://sky.with.us.in/payment/notify
    notify-url: http://skyapi.with.us.in/pay/notify/call
    pid: 1010